name: niklaar
description: "A new Flutter project."

publish_to: 'none' # 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  loading_overlay: ^0.4.2
  provider: ^6.1.4
  smooth_page_indicator: ^1.2.1
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  another_flushbar: ^1.12.30
  flutter_portal: ^1.1.4
  auto_route: ^7.8.4
  flutter_platform_widgets: ^8.0.0
  country_picker: ^2.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
